global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Configuration;
global using LinkDev.Talabat.Domain.Common;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using LinkDev.Talabat.Domain.Entities.Products;
global using LinkDev.Talabat.Infrastructure.Persistence.Data.Config.Base;
global using LinkDev.Talabat.Infrasteucture.Persistence;
global using LinkDev.Talabat.Infrastructure.Persistence;
